webdriver:
  desired_capabilities:
    acceptInsecureCerts: True
  options: [ --allow-running-insecure-content, --ignore-certificate-errors , ]



portal_ui:

  base_url: https://www.dev.quicklly.com
  admin_user: testaccount@quicklly.com
  admin_password: 123456

