webdriver:
  desired_capabilities:
    acceptInsecureCerts: True
  options: [ --allow-running-insecure-content, --ignore-certificate-errors , ]



portal_ui:

  base_url: http://dev.goquicklly.com/
  admin_user: Excellence Delivered
  admin_password: 1234

